stages:
  processing:
    cmd: python src/processing.py data/census.csv
    deps:
    - data/census.csv
    - src/processing.py
    params:
    - processing.primary_data
    - processing.raw_data
    outs:
    - data/cleaned_census.csv
  segregation:
    cmd: python src/segregation.py
    deps:
    - data/cleaned_census.csv
    - src/segregation.py
    params:
    - processing.primary_data
    - segregation.train_data
    - segregation.test_data
    - segregation.test_size
    - segregation.random_state
    outs:
    - data/train_data.csv
    - data/test_data.csv
  train:
    cmd: python src/train.py
    deps:
    - data/train_data.csv
    - src/train.py
    params:
    - train.label
    - train.categorical_features
    - train.loss
    - train.learning_rate
    - train.max_depth
    - train.random_state
    - train.model
    outs:
    - models/census_model_v1