processing:
  raw_data: data/census.csv
  primary_data: data/cleaned_census.csv
segregation:
  train_data: data/train_data.csv
  test_data: data/test_data.csv
  test_size: 0.2
  random_state: 24
train:
  label: salary
  categorical_features:
    - workclass
    - education
    - marital-status
    - occupation
    - relationship
    - race
    - sex
    - native-country
  loss: log_loss
  learning_rate: 0.1
  max_depth: 10
  random_state: 24
  model: models/census_model_v1
evaluate:
  metrics: reporting/metrics.json
  slice_metrics: reporting/slice_metrics.json